#release:
#  github:
#    owner: 'https:'
#brew:
#  install: bin.install "goreleaser-test"
project_name: goreleaser-test
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  main: main.go
  binary: goreleaser-test
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
    linux: Tux
  files:
  - README*
#snapshot:
#  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

release:
  draft: false
  github:
    owner: sklevenz
    name: goreleaser-test
    api_url: https://api.github.com/
    upload_url: https://uploads.github.com/
    download_url: https://github.com/

brew:
  folder: Formula
  caveats: "How to use this binary"
  homepage: "https://example.com/"
  description: "Software to create fast and easy drum rolls."
  test: |
    system "#{bin}/goreleaser-test"
  install: |
    bin.install "goreleaser-test"
  github:
    owner: cloudfoundry
    name: hombrew-cp-core
    api_url: https://api.github.com/
    upload_url: https://uploads.github.com/
    download_url: https://github.com/
