#!/usr/bin/env bash

TAG=$1

git tag -d $TAG
git push origin :refs/tags/$TAG

git add .
git commit -m "dev"
git push

git tag -a $TAG -m "a new release"
git push origin $TAG

goreleaser --rm-dist --debug

tree dist

./dist/go-release-test_0.1.0_macOS_64-bit/go-release-test
