#!/usr/bin/env bash

TAG=$1

git tag -d $TAG
git push origin :refs/tags/$TAG

git add .
git commit -m "dev $(date "+DATE: %Y-%m-%d TIME: %H:%M:%S")"
git push

git tag -a $TAG -m "a new release"
git push origin $TAG

goreleaser --rm-dist --debug
